- name: Enable firewalld
  systemd: 
    name: firewalld
    enabled: yes
    masked: no
    state: started 
    daemon-reload: yes

- name: Allow SSH traffic
  firewalld: 
    service: ssh
    permanent: true
    immediate: true 
    state: enabled
